version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  default_reviewers:
    - mijailr
  default_assignees:
    - mijailr
    
