name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn install
      
    - name: Linter
      run: yarn lint
    
    - name: Run tests
      run: yarn test
